### ISSUE TITLE
Scrubbing unmutes the sound

### ISSUE THREAD

**Issue by impressivewebs** [BMSVieira/moovie.js#12]
If you mute the audio, then scrub to a new location of the video, this unmutes the audio. This seems unintuitive to me. I believe the audio should stay muted while scrubbing until the user unmutes it.

**Comment by BMSVieira** [comment]
@impressivewebs 

I agree, it is definitely a bug.
It will be fixed in the next commits.

Thank you!

**Comment by BMSVieira** [comment]
@impressivewebs 
Thank you, it's fixed!

**Comment by impressivewebs** [comment]
@BMSVieira 

Fantastic! Thanks for the quick response. Works perfectly now.

BTW - I'll be linking it in [my newsletter](https://webtoolsweekly.com/) this week. 😄
