### ISSUE TITLE
Mute sound in demo then unmute sound sometimes results in no sound.

### ISSUE THREAD

**Issue by travis5491811** [BMSVieira/moovie.js#13]
Hello,

I found this while checking out the demo. When i mute the demo and then unmute, sometimes the sound does not come back until i adjust the volume even though the volume is all the way up.

Mac Catalina 10.15.7
Google Chrome Version 89.0.4389.114 (Official Build) (x86_64)

1. Open [demo](https://mooviejs.com/) in a fresh incognito browser session
2. Play demo
2. Skip forward
3. Click mute sound button
4. Click unmute sound button
5. Note that sound is no longer muted, and volume is still all the way up. But there is no sound.

I don't have a tool on my mac to show you the actual sound feedback so you can also observe the loss of sound. The issue is consistent in fresh browser session.

![moviejs 2021-04-12 at 09 56 04](https://user-images.githubusercontent.com/41482601/114406305-6e5d0180-9b75-11eb-8038-4975760e9a3c.gif)

**Comment by BMSVieira** [comment]
I already managed to replicate, thanks for your time, it is certainly a bug! 
I will fixed it as soon as possible :)
