### ISSUE TITLE
Add Option for skip certain parts of the video

### ISSUE THREAD

**Issue by SrPatinhas** [BMSVieira/moovie.js#18]
It would be a nice feature to have, having a button that would appear if the option was selected or had any value, being able to skip from a certain time to another, like when its a recap or the intro of a episode, or even for the next episode at a certain time.

Something like the netflix player or the amazon prime.

for the settings would be like this:
```
var demo = new Moovie({
    selector: "#example",
    dimensions: {
         width: "100%"
    },
    config: {
        ...
    },
    skip: [
        {
            begin: 20, //seconds
            end: 60 //seconds
        },
        {
            begin: 2400, //seconds
            link: "source.of/next.video.mp4" //seconds
        },
    ]
```

**Comment by BMSVieira** [comment]
Yes, i agree!
Already thought about that when i saw the "skip intro" from netflix..
Basically, giving people a chance to define events starting from a specific time.

The tricky part will be the button's positioning and appearance, let people define where the button will appear, maybe using pre-defined positions like "top-left-corner" or "bottom-center" and CSS Custom Properties.. dont know, i have to think deeply about it 

but it is on the to-do list for sure! thank you!

**Comment by SrPatinhas** [comment]
it could be that or in the CSS config would be defined by the dev that integrated the code, maybe this button would have its own class and would be changed on the css.
But we could add another option in the skip config were the dev would define the type of button, because we could have a "skip intro" on the bottom right of the screen, but then, the next episode could be a arrow for example in the middle of the right side of the screen.

**Comment by BMSVieira** [comment]
Yeah, for sure it has to have some kind of `buttonContent` where he (dev) can write whatever he wants, text, icons, font Awesome, everything, and a `buttonClass` where he can add his own classes to match the website's current style.

Great ideas! thank you!

**Comment by BMSVieira** [comment]
Added! (#21) 👍🏼
