### ISSUE TITLE
Loading and progress bar problems

### ISSUE THREAD

**Issue by SrPatinhas** [BMSVieira/moovie.js#19]
When seeking a new position on the progress bar, the loading does not appear, or any type of information.

![image](https://user-images.githubusercontent.com/6379218/115129926-805dfa80-9fe2-11eb-92c7-9a7ec6f3a145.png)
And when using another type of media, like with the webtorrent example, the progress bar should be fulfilling the parts that are available, or at least, follow the current time ball.

**Comment by BMSVieira** [comment]
Yup, buffer handler needs rework!
