### ISSUE TITLE
This project is in desperate need of specs

### ISSUE THREAD

**Issue by nskazki** [BMSVieira/moovie.js#3]
Thanks for putting it together - looking really neat, with lots of features too. But if you don't figure out specs shortly you may end up fixing what has been fixed over and over again. And the more features are to be introduced, the more likely everything is to start falling apart... believe me I've been there.

**Comment by BMSVieira** [comment]
@nskazki Hey, thanks.
Yes, I started this project a few days ago and I'm still organizing things, but I have a perfect idea of what I want.
I will definitely start working on it, I will also develop a changelog to keep everyone informed of what has been done with each release.
My main concern is to develop a strong foundation to achieve a lot with little code in the future.
