### ISSUE TITLE
Subtitles settings

### ISSUE THREAD

**Issue by SrPatinhas** [BMSVieira/moovie.js#7]
We could be able to costumize the captions, like, text-border, color, position

When the controls are showing, the subtitles should update the position to be seen every time.

![image](https://user-images.githubusercontent.com/6379218/111525658-c27eec80-8755-11eb-8107-3d7e695e60be.png)

Even when in fullscreen, the subtitles size, are bigger then it should. maybe calculate with a smaller ratio?

**Comment by BMSVieira** [comment]
Hey,
Thanks, I will keep that in mind in the next updates.

Regarding subtitles, there are shortcuts that allow you to change the placement and modify the size. 

| Key | Description |
| --- | --- |
| `Shift`+`PageUp`| Increase caption's size|
| `Shift`+`PageDown`| Decrease caption's size|
| `Shift`+`ArrowUp`| Move caption up|
| `Shift`+`ArrowDown`| Move caption down|

However, I noticed some kind of conflict with `Shift + PageUp / Down` that doesn't work on different types of keyboards. I will probably change those  shortcuts in the next commit.
