### ISSUE TITLE
Mute and unmute audio

### ISSUE THREAD

**Issue by subhero24** [BMSVieira/moovie.js#9]
When muting and unmuting the audio, audio level jumps to 1. Would be nice if it jumped to the audio level before muting the audio instead of max.

**Comment by BMSVieira** [comment]
Hey, 
It's on the "to-do" list, it will probably be released in a few days

**Comment by subhero24** [comment]
Thanks! If you want me to take a stab at this with a PR, let me know. Be happy to do it.

**Comment by BMSVieira** [comment]
@subhero24,
Thank you, it was not necessary, as it was already in my plans to work on it.
in fact, it has been launched in the last commit along with some improvements to the volume range input, try it out! Thanks.
